version: '3.8'

services:
  task-management-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    environment:
      - VITE_USE_MOCK_API=true
    restart: always
