import { Task } from '../types/task';
import { User } from '../types/auth';

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Alex Morgan',
    email: 'alex.morgan@company.com',
    role: 'Admin',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&h=120&q=80',
  },
  {
    id: 'user-2',
    name: 'Sarah Chen',
    email: 'sarah.chen@company.com',
    role: 'Project Manager',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80',
  },
  {
    id: 'user-3',
    name: 'David Miller',
    email: 'david.miller@company.com',
    role: 'Developer',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80',
  },
  {
    id: 'user-4',
    name: 'Emily Taylor',
    email: 'emily.taylor@company.com',
    role: 'Developer',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=120&h=120&q=80',
  },
];

export const INITIAL_MOCK_TASKS: Task[] = [
  {
    id: 'task-101',
    title: 'Fix login button styling on mobile',
    description: 'The login button looks misaligned on smaller screens. Need to fix flex layout and padding.',
    assignedUser: MOCK_USERS[0],
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-08-28',
    createdAt: '2026-08-20T09:00:00.000Z',
    tags: ['Bug', 'UI', 'Mobile'],
  },
  {
    id: 'task-102',
    title: 'Update dashboard header layout',
    description: 'Add user avatar dropdown menu and fix spacing between action buttons.',
    assignedUser: MOCK_USERS[1],
    priority: 'High',
    status: 'Completed',
    dueDate: '2026-08-24',
    createdAt: '2026-08-18T14:30:00.000Z',
    tags: ['Dashboard', 'Frontend'],
  },
  {
    id: 'task-103',
    title: 'Add unit tests for login page',
    description: 'Write test cases for email validation, wrong password error message, and redirect flow.',
    assignedUser: MOCK_USERS[2],
    priority: 'Medium',
    status: 'Pending',
    dueDate: '2026-08-30',
    createdAt: '2026-08-22T11:15:00.000Z',
    tags: ['Testing', 'QA'],
  },
  {
    id: 'task-104',
    title: 'Fix search bar lag on mobile',
    description: 'Debounce search keystrokes so the task list doesn’t re-render on every letter typed.',
    assignedUser: MOCK_USERS[3],
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-08-27',
    createdAt: '2026-08-21T16:00:00.000Z',
    tags: ['Performance', 'React'],
  },
  {
    id: 'task-105',
    title: 'Setup staging build script',
    description: 'Create docker build script and github action for automatic deployment to staging.',
    assignedUser: MOCK_USERS[0],
    priority: 'Medium',
    status: 'Pending',
    dueDate: '2026-09-02',
    createdAt: '2026-08-23T10:45:00.000Z',
    tags: ['DevOps', 'Docker'],
  },
  {
    id: 'task-106',
    title: 'Update user API endpoints',
    description: 'Clean up user profile service calls and handle 401 unauthenticated response properly.',
    assignedUser: MOCK_USERS[2],
    priority: 'High',
    status: 'Completed',
    dueDate: '2026-08-25',
    createdAt: '2026-08-19T08:20:00.000Z',
    tags: ['API', 'Backend'],
  },
  {
    id: 'task-107',
    title: 'Fix dark mode color contrast',
    description: 'Check contrast ratio on task priority badges and modal background text in dark mode.',
    assignedUser: MOCK_USERS[1],
    priority: 'Low',
    status: 'Completed',
    dueDate: '2026-08-22',
    createdAt: '2026-08-17T13:10:00.000Z',
    tags: ['CSS', 'Design'],
  },
  {
    id: 'task-108',
    title: 'Add status column view for task board',
    description: 'Create Kanban view with columns for Pending, In Progress, and Completed tasks.',
    assignedUser: MOCK_USERS[3],
    priority: 'Low',
    status: 'Pending',
    dueDate: '2026-09-05',
    createdAt: '2026-08-24T15:00:00.000Z',
    tags: ['Kanban', 'Feature'],
  },
];
